/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/portal.glb -o src/app/components/canvas/Portal.js 
*/
"use client";
import React from 'react'
import { Canvas } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { DoubleSide } from 'three'

export function Model(props) {
  const { nodes, materials } = useGLTF('/portal.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[-1.079, 0.476, 1.563]} scale={[0.831, 1.093, 1.019]} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[3.099, 0.476, 1.563]} scale={[0.831, 1.093, 1.019]} />
      <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[3.104, 1.144, 1.597]} scale={[0.808, 1, 1.529]} />
      <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[-1.102, 1.144, 1.597]} scale={[0.792, 0.98, 1.414]} />
      <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[-1.091, 1.72, 1.597]} rotation={[0, 0, -0.023]} scale={[0.865, 2.246, 1.047]} />
      <mesh geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[3.102, 1.758, 1.597]} scale={[0.828, 2.149, 1.047]} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[-1.053, 2.35, 1.607]} rotation={[0, 0, -0.023]} scale={[0.819, 0.958, 1]} />
      <mesh geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} position={[3.132, 2.35, 1.607]} rotation={[0, 0, -0.023]} scale={[0.819, 0.958, 1]} />
      <mesh geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[-1.031, 2.814, 1.58]} rotation={[0, 0, -0.023]} scale={[0.715, 1.522, 1.528]} />
      <mesh geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} position={[3.149, 2.819, 1.607]} rotation={[0, 0, -0.023]} scale={[0.722, 1.522, 1.241]} />
      <mesh geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[-1.031, 3.381, 1.58]} rotation={[-0.004, -0.015, -0.196]} scale={[0.715, 1.63, 1.127]} />
      <mesh geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} position={[3.131, 3.413, 1.58]} rotation={[0.001, 0.013, 0.181]} scale={[0.715, 1.63, 0.994]} />
      <mesh geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} rotation={[-0.003, -0.016, -0.088]} />
      <mesh geometry={nodes.Cube013.geometry} material={nodes.Cube013.material} position={[-0.972, 3.872, 1.713]} rotation={[-0.018, 0.029, 2.82]} scale={[-1.019, -0.907, -1.423]} />
      <mesh geometry={nodes.Cube014.geometry} material={nodes.Cube014.material} position={[3.085, 3.908, 1.713]} rotation={[0.036, -0.073, -2.833]} scale={[-1.025, -1.184, -1.423]} />
      <mesh geometry={nodes.Cube015.geometry} material={nodes.Cube015.material} position={[-0.802, 4.28, 1.713]} rotation={[-0.015, 0.034, 2.742]} scale={[-1.218, -0.929, -1.771]} />
      <mesh geometry={nodes.Cube016.geometry} material={nodes.Cube016.material} position={[2.952, 4.28, 1.713]} rotation={[-0.066, -0.106, -2.816]} scale={[-1.563, -1.417, -1.703]} />
      <mesh geometry={nodes.Cube017.geometry} material={nodes.Cube017.material} position={[-2.151, 0.617, 1.679]} rotation={[0.008, 0.034, -0.346]} scale={[1.738, 1.931, 1.442]} />
      <mesh geometry={nodes.Cube018.geometry} material={nodes.Cube018.material} position={[4.739, 1.192, 1.052]} rotation={[0.152, -0.016, 0.502]} scale={[1.708, 1.822, 1.432]} />
      <mesh geometry={nodes.Cube019.geometry} material={nodes.Cube019.material} position={[-0.5, 5.039, 1.654]} rotation={[-0.042, -0.017, -0.503]} scale={[1.026, 1, 1.351]} />
      <mesh geometry={nodes.Cube020.geometry} material={nodes.Cube020.material} position={[2.461, 5.312, 1.521]} rotation={[0, -0.002, 0.575]} scale={[-0.955, -0.695, -0.674]} />
      <mesh geometry={nodes.Cube021.geometry} material={nodes.Cube021.material} position={[2.595, 5.098, 1.521]} rotation={[0, 0, 0.475]} scale={[1.026, 1, 1.351]} />
      <mesh geometry={nodes.Cube025.geometry} material={nodes.Cube025.material} position={[1.094, 5.98, 1.59]} rotation={[0, 0.007, 1.549]} scale={[1.476, 1.525, 1.351]} />
      <mesh geometry={nodes.Cube026.geometry} material={nodes.Cube026.material} position={[1.538, 5.929, 1.521]} rotation={[0, 0, 1.421]} scale={[1.133, 1.446, 1.27]} />
      <mesh geometry={nodes.Cube027.geometry} material={nodes.Cube027.material} position={[0.638, 5.929, 1.596]} rotation={[0, 0, 1.689]} scale={[1.268, 1.223, 1.351]} />
      <mesh geometry={nodes.Cube028.geometry} material={nodes.Cube028.material} position={[2.325, 5.461, 1.456]} rotation={[0.003, 0.01, 0.686]} scale={[1.093, 0.705, 1.849]} />
      <mesh geometry={nodes.Cube030.geometry} material={nodes.Cube030.material} position={[2.212, 5.623, 1.491]} rotation={[-0.003, 0.058, 0.906]} scale={[1.074, 0.693, 1.817]} />
      <mesh geometry={nodes.Cube023.geometry} material={nodes.Cube023.material} position={[1.961, 5.8, 1.526]} rotation={[0, 0, 1.119]} scale={[1.168, 1.191, 1.318]} />
      <mesh geometry={nodes.Cube024.geometry} material={nodes.Cube024.material} position={[0.292, 5.836, 1.612]} rotation={[-0.017, 0.003, 1.9]} scale={[-0.942, -0.992, -1.377]} />
      <mesh geometry={nodes.Cube029.geometry} material={nodes.Cube029.material} position={[-0.035, 5.706, 1.67]} rotation={[0.057, -0.009, -0.873]} scale={[1.243, 0.803, 2.103]} />
      <mesh geometry={nodes.Cube022.geometry} material={nodes.Cube022.material} position={[-0.192, 5.494, 1.615]} rotation={[0.017, 0.045, -0.754]} scale={[0.992, 0.64, 1.678]} />
      <mesh geometry={nodes.Cube031.geometry} material={nodes.Cube031.material} position={[-0.354, 5.312, 1.619]} rotation={[-0.001, -0.001, -0.408]} scale={[-0.955, -0.695, -0.674]} />
      <mesh geometry={nodes.Plane.geometry} position={[1.027, 2.801, 1.581]} rotation={[-1.552, 0, 0.033]} scale={[1.639, 1.638, 2.679]}>
        <meshStandardMaterial side={DoubleSide} color={nodes.Plane.material?.color || "#ffffff"} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/portal.glb')

export default function Portal() {
  return (
    <div className="relative w-full" style={{ minHeight: "1000px" }}>
      {/* Canvas layer - in front */}
      <div className="absolute inset-0 z-10" style={{ pointerEvents: "none" }}>
        <Canvas camera={{ position: [0, 2, 15], fov: 45 }}>
          <ambientLight intensity={0.9} />
          <directionalLight position={[5, 5, 5]} intensity={1} />
          <Model position={[0, -3, 0]} />
        </Canvas>
      </div>
    </div>
  );
}
